CREATE DATABASE IF NOT EXISTS `racs` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USERNAME}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON `racs`.* TO '${DB_USERNAME}'@'%';
FLUSH PRIVILEGES;
