stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository

test:
  stage: test
  image: eclipse-temurin:25-jdk
  script:
    - ./mvnw $MAVEN_OPTS test