package uk.co.eightmile.racs.permissions;

public enum Authority {
    ADMIN,
    READER,

    PAGE_USER,
    READ_USER,
    CREATE_USER,
    UPDATE_USER,
    DELETE_USER,

    PAGE_CAMPAIGN,
    READ_CAMPAIGN,
    CREATE_CAMPAIGN,
    UPDATE_CAMPAIGN,
    DELETE_CAMPAIGN,

    PAGE_READER,
    READ_READER,
    CREATE_READER,
    UPDATE_READER,
    DELETE_READER,

    PAGE_SCAN,
    READ_SCAN,
    CREATE_SCAN,
    UPDATE_SCAN,
    DELETE_SCAN,

    PAGE_LOCATION,
    READ_LOCATION,
    CREATE_LOCATION,
    UPDATE_LOCATION,
    DELETE_LOCATION,

    PAGE_ROLE,
    READ_ROLE,
    CREATE_ROLE,
    UPDATE_ROLE,
    DELETE_ROLE,

    PAGE_CARD,
    READ_CARD,
    CREATE_CARD,
    UPDATE_CARD,
    DELETE_CARD,

    PAGE_REPORT,
    CREATE_GENERAL_SUMMARY_REPORT,
    CREATE_DAILY_USAGE_REPORT,
    CREATE_LOCATION_REPORT,
    CREATE_MULTIPLE_SCAN_REPORT,
    CREATE_READER_REPORT,
    CREATE_SERIAL_NUMBER_REPORT,
}
